/**
 * CONFIG - Auto-generated by build.js
 * Client: Stuart Martin County Chamber of Commerce
 * Do not edit manually - modify clients/stuart/client.json instead
 */

const CONFIG = {
    "mapbox": {
        "accessToken": "pk.eyJ1IjoicnlhbmRvbHBoanIiLCJhIjoiY21sOHI2OXRvMGE2ejNtcTMyajh0bWJtNCJ9.fDd6RAIarBzArdbZu8gfCA",
        "style": "mapbox://styles/mapbox/streets-v12",
        "center": [
            -80.2531,
            27.1975
        ],
        "zoom": 13,
        "minZoom": 3,
        "maxZoom": 18
    },
    "client": {
        "name": "Chamber of Commerce Interactive Map",
        "logoPath": "assets/logos/client-logo.png",
        "logoAlt": "Stuart Martin County Chamber of Commerce Logo"
    },
    "dolphLogo": {
        "logoPath": "assets/logos/dolph-logo.jpg",
        "logoAlt": "Dolph Map Company",
        "link": "https://dolphmap.com",
        "contact": {
            "name": "Marsha Duvall",
            "phone": "(954) 695-0327",
            "email": "mduvall@dolphmap.com"
        }
    },
    "banners": {
        "banner1": {
            "image": "assets/banners/premium/sponsor.jpg",
            "link": "#",
            "alt": "Premium Sponsor"
        },
        "banner2": [],
        "slideshow": {
            "interval": 5000,
            "fadeTransition": 1000
        }
    },
    "data": {
        "csvPath": "data/advertisers.csv"
    },
    "markers": {
        "defaultColor": "#1a5276",
        "clusterEnabled": false,
        "customIcon": null
    },
    "cityLabel": {
        "name": "STUART",
        "position": [
            -80.2531,
            27.19
        ],
        "hideFromDefaultLabels": "Stuart",
        "hideAtZoom": 14
    },
    "chamberCallout": {
        "position": [
            -80.24,
            27.185
        ],
        "showAtZoom": 12
    }
};

// Verify that CONFIG is properly defined
if (typeof CONFIG === 'undefined') {
    console.error('ERROR: CONFIG object is not defined!');
}
