/**
 * CONFIG - Auto-generated by build.js
 * Client: Stuart Martin County Chamber of Commerce
 * Do not edit manually - modify clients/stuart/client.json instead
 */

const CONFIG = {
    "mapbox": {
        "accessToken": "pk.eyJ1IjoicnlhbmRvbHBoanIiLCJhIjoiY21sOHI2OXRvMGE2ejNtcTMyajh0bWJtNCJ9.fDd6RAIarBzArdbZu8gfCA",
        "style": "mapbox://styles/mapbox/streets-v12",
        "center": [
            -80.2531,
            27.203
        ],
        "zoom": 12,
        "minZoom": 3,
        "maxZoom": 18
    },
    "client": {
        "name": "Chamber of Commerce Interactive Map",
        "logoPath": "assets/logos/client-logo.svg",
        "cornerLogoPath": "assets/logos/Stuart Logo Vertical.png",
        "logoAlt": "Stuart Martin County Chamber of Commerce Logo"
    },
    "dolphLogo": {
        "logoPath": "assets/logos/dolph-logo.jpg",
        "logoAlt": "Dolph Map Company",
        "link": "https://dolphmap.com",
        "contact": {
            "name": "Marsha Duvall",
            "phone": "(954) 695-0327",
            "email": "mduvall@dolphmap.com"
        }
    },
    "banners": {
        "banner1": {
            "image": "assets/banners/premium/cbd.jpg",
            "link": "https://www.closetsbydesign.com",
            "alt": "Closets by Design"
        },
        "banner2": [
            {
                "image": "assets/banners/slideshow/apex.jpg",
                "link": "https://www.apexpaversandpools.com",
                "alt": "Apex Pavers & Pools"
            },
            {
                "image": "assets/banners/slideshow/bam.jpg",
                "link": "https://www.beamanbyland.com",
                "alt": "Be A Man Buy Land"
            },
            {
                "image": "assets/banners/slideshow/barn728.jpg",
                "link": "https://www.barn-theatre.com",
                "alt": "The Barn Theatre"
            },
            {
                "image": "assets/banners/slideshow/ccc.jpg",
                "link": "https://www.stuartcardiology.com",
                "alt": "Stuart Cardiology Group"
            },
            {
                "image": "assets/banners/slideshow/chap.jpg",
                "link": "https://www.stuartmartinchamber.org/",
                "alt": "Stuart Martin County Chamber of Commerce"
            },
            {
                "image": "assets/banners/slideshow/eg.jpg",
                "link": "https://www.elitegasco.com",
                "alt": "Elite Gas Contractors"
            },
            {
                "image": "assets/banners/slideshow/ferr.jpg",
                "link": "https://www.ferreiraconstruction.com",
                "alt": "Ferreira Construction Company"
            },
            {
                "image": "assets/banners/slideshow/fg.jpg",
                "link": "https://www.ferrellgas.com",
                "alt": "Ferrellgas"
            },
            {
                "image": "assets/banners/slideshow/hobe728.jpg",
                "link": "https://www.hobesoundfarms.com",
                "alt": "Hobe Sound Farms"
            },
            {
                "image": "assets/banners/slideshow/martier728.jpg",
                "link": "https://www.grandemartier.com",
                "alt": "La Grande Martier"
            },
            {
                "image": "assets/banners/slideshow/mcbride.jpg",
                "link": "https://mcbridelegalgroup.com/",
                "alt": "McBride Legal Group, P.A."
            },
            {
                "image": "assets/banners/slideshow/ns.jpg",
                "link": "https://www.newwaverealestategroup.com",
                "alt": "New Wave Real Estate Group"
            },
            {
                "image": "assets/banners/slideshow/nw.jpg",
                "link": "https://www.newwaverealestategroup.com",
                "alt": "New Wave Real Estate Group"
            },
            {
                "image": "assets/banners/slideshow/Precision Disposal 728.jpg",
                "link": "https://www.treasurecoastdumpsterrental.com",
                "alt": "Precision Disposal of South Florida"
            },
            {
                "image": "assets/banners/slideshow/rare.jpg",
                "link": "https://store.rareearthgallery.com",
                "alt": "Rare Earth Gallery"
            },
            {
                "image": "assets/banners/slideshow/sandhill.jpg",
                "link": "https://www.sandhillcove.com",
                "alt": "Sandhill Cove Retirement Living"
            },
            {
                "image": "assets/banners/slideshow/sovava.jpg",
                "link": "https://www.thesovana.com",
                "alt": "The Sovana at Stuart"
            },
            {
                "image": "assets/banners/slideshow/wild728.jpg",
                "link": "https://www.wildsidepawnandjewelry.com",
                "alt": "Wild Side Pawn and Jewelry"
            }
        ],
        "slideshow": {
            "interval": 5000,
            "fadeTransition": 1000
        }
    },
    "data": {
        "csvPath": "data/advertisers.csv"
    },
    "markers": {
        "defaultColor": "#1a5276",
        "clusterEnabled": false,
        "customIcon": null
    },
    "cityLabel": {
        "name": "STUART",
        "position": [
            -80.245,
            27.197
        ],
        "hideFromDefaultLabels": "Stuart",
        "hideAtZoom": 14
    },
    "chamberCallout": {
        "position": [
            -80.24,
            27.208
        ],
        "showAtZoom": 12
    }
};

// Verify that CONFIG is properly defined
if (typeof CONFIG === 'undefined') {
    console.error('ERROR: CONFIG object is not defined!');
}
